on:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/publish-charts.yaml
      - devopscoop
      - pipeline.sh
  push:
    branches: [main]
    paths:
      - .github/workflows/publish-charts.yaml
      - devopscoop
      - pipeline.sh
  workflow_dispatch: {}
jobs:
  publish-charts:
    container:
      image: alpine/helm:3.17.2
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: |
          echo "helm_registry=ghcr.io" >> $GITHUB_ENV
          echo "helm_username=${{ github.actor }}" >> $GITHUB_ENV
          echo "helm_password=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "git_repo_owner=$GITHUB_REPOSITORY_OWNER" >> $GITHUB_ENV
      - run: ./pipeline.sh
      - if: github.event_name == 'push'
        run: ./pipeline.sh push
